.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH OPENBVE 6 "February 16, 2009" OpenBVE
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH "NAME"
OpenBVE \- train/railway simulator and game
.SH "SYNOPSIS"
.B openbve
.br
.SH "DESCRIPTION"
OpenBVE is a public domain railway/train simulator.

The simulation is restricted to following a pre-determined route, with
the focus being on driving realism.

The simulator is backwards compatible with existing 'BVE Trainsim'
train and route datafiles readily available for free-as-in-beer.  It
is cross-platform using CLI and Mono.

.SH "DATAFILES"
Two elements are required, a route, and a train (actually just a cab and performance metrics).

+ Railway/
.br
| + Routes/
.br
|   + foo/
.br
|     + foo.csv
.br
+ Trains/
.br
  + bar.dat

.br
.SH "AUTHOR"
OpenBVE was written by Michelle Boucquemont <reschanger@gmail.com>
.TP
This manual page was written for Debian/Ubuntu by Paul Sladen <ubuntu@paul.sladen.org>

.br
.SH "SEE ALSO"
.BR http://openbve.uuuq.com/
.br

